---

- name: Atualizar o sistema
  import_playbook: tasks/update-system.yml
- name: Instalar o KDE Plasma
  import_playbook: tasks/install-plasma.yml
- name: Instalação de software a partir dos repositórios
  import_playbook: tasks/install-foss.yml
