---

- name: Configurar roles do Ansible
  import_playbook: tasks/ansible-setup-roles.yml
- name: Atualizar o sistema
  import_playbook: tasks/update-system.yml
- name: Instalar o KDE Plasma
  import_playbook: tasks/install-plasma.yml
- name: Instalação de software a partir dos repositórios
  import_playbook: tasks/install-foss.yml
- name: Instalação de software a partir do Flatpak
  import_playbook: tasks/install-flatpak.yml
- name: Configuração de rede com iwd e vnstat
  import_playbook: tasks/network-settings.yml
- name: Instalação de pacotes proprietários sortidos
  import_playbook: tasks/install-other-packages.yml
- name: Instalação do Tailscale
  import_playbook: tasks/install-tailscale.yml
