- hosts: localhost
  become: true
  tasks:
    - name: Instalação de software desktop a partir dos repositórios
      dnf:
        name:
          - gimp
          - inkscape
          - libreoffice-core
          - libreoffice-data
          - vlc
          - geany
          - qalculate-gtk
          - wine
          - kdenlive
          - qbittorrent
    - name: Instalação de software de aúdio
      dnf:
        name:
          - lmms
          - qjackctl
          - qsynth
          - fluidsynth
          - hydrogen
          - audacity
          - Carla-vst
    - name: Instalação de ferramentas de terminal
      dnf:
        name:
          - zsh
          - weechat
          - neovim
          - emacs
          - tmux
          - nethack  # importante demais
          - pdftk-java
          - neofetch
    - name: Instalação de ferramentas de desenvolvimento
      dnf:
        name:
          - gcc
          - gdb
          - make
          - octave
          - hugo
    - name: Instalação de ambiente de virtualização e emulação
      dnf:
        name:
          - virt-manager
          - dosbox
          - qmc2
          - VirtualBox
          - qemu-system-ppc  # emulação de Mac clássico
    - name: Instalação de utilitários e ferramentas de manutenção
      dnf:
        name:
          - gparted
          - htop
          - nmap
          - wireshark
          - qemu-img
          - edid-decode
          - monitor-edid
          - ncdu
    - name: Usuário nos grupos para poder usar o VirtualBox
      user:
        name: renan
        groups: libvirt, vboxusers
        append: yes
