- hosts: localhost
  become: true
  tasks:
    - name: Instalação do KDE Plasma
      dnf:
        name: '@KDE Plasma Workspaces'
    - name: Desativar o GDM (GNOME Display Manager)
      service:
        name: gdm
        enabled: no
    - name: e ativar o SDDM
      service:
        name: sddm
        enabled: yes
    - name: Informar o usuário
      debug:
        msg: "Você precisará alterar a sessão na tela de login, caso ainda não o tenha feito."
