- hosts: localhost
  become: true
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
  tasks:
    - name: ativar o repo do Tailscale
      # não encontrei forma de fazer isso nativamente no Ansible.
      ansible.builtin.command: dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    - name: instalar o Tailscale
      dnf:
        name:
          - tailscale
    - name: ativar o serviço no systemd
      service:
        name: tailscaled
        enabled: yes
    - name: rodar o serviço no systemd
      service:
        name: tailscaled
        state: started 
    - name: configurar sysctl para usar essa máquina como roteador no Tailscale
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: yes
        state: present
        reload: yes
        ignoreerrors: yes
      with_dict: '{{ sysctl_config }}'

    - name: informar o usuário
      debug:
        msg: execute "sudo tailscale up" para configurar o Tailscale, se você quiser usar essa máquina como exit node, informe "--advertise-exit-node"
